const data = {
	products: [
		{
			name: 'Nike Slim shirt',
			slug: 'nike-slim-shirt',
			category: 'Shirts',
			img: '/images/p1.png',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'quality shirt',
		},
		{
			name: 'Zero Regular shirt',
			slug: 'zero-regular-shirt',
			category: 'Shirts',
			img: '/images/p2.png',
			price: 220,
			countInStock: 16,
			brand: 'Zero',
			rating: 4.6,
			numReviews: 12,
			description: 'Cotton full sleeves shirt',
		},
		{
			name: 'Nike Slim Pant',
			slug: 'nike-slim-pant',
			category: 'Pants',
			img: '/images/p3.png',
			price: 320,
			countInStock: 20,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 8,
			description: 'Jeans and cotton fits',
		},
		{
			name: 'Vanheusen Cotton Pant',
			slug: 'vanheusen-cotton-pant',
			category: 'Pants',
			img: '/images/p4.png',
			price: 350,
			countInStock: 22,
			brand: 'Vanhesuen',
			rating: 4.0,
			numReviews: 18,
			description: 'Cotton fits high quality',
		},
	],
};

export default data;
